# **Random Numbers in Python**

Computers generated pesudo random numbers. Pesudo Random Number Generators(PRNGs) are based on computational algorithms that can produce apparently random results. Python, like any other programming language uses PRNGs. Python's random generation is based upon Mersenne Twister algorithm that produces 53-bit precision floats.

### **Required Libraries**

In [10]:
import numpy as np

### **A Quick Example...**

In [11]:
import numpy as np
np.random.randint(10,50)

46

In [12]:
np.random.random()

0.4945899295333641

### **np.random.randint()**

In [13]:
#Generate a random integer between 10 to 80
#low = 10 (inclusive); high = 80 (exclusive)
print(np.random.randint(10,80))

print(np.random.randint(1999,2022))

#Generate random integers between 10 to 80
#2D Array of size 2x3
print(np.random.randint(10,80,(2,3)))

#1D Array of size 10
print(np.random.randint(10,80,10))

38
2015
[[39 18 10]
 [50 46 26]]
[21 64 72 43 59 61 64 79 23 35]


### **np.random.random()**

In [14]:
#Generate a random float in the interval [0.0,1.0)
print(np.random.random())

#Generate random floats in the interval [0.0,1.0) 
#1D Array of size 5
print(np.random.random(5))

#2D array of size 2x2
print(np.random.random((2,2)))

0.7787288082639929
[0.58390137 0.18263144 0.82608225 0.10540183 0.28357668]
[[0.06556327 0.05644419]
 [0.76545582 0.01178803]]


### **np.random.get_state()**

In [15]:
#Get the internal state of the generator
np.random.get_state()

('MT19937', array([1649622067, 2194114323, 4264962802, 3494850638, 3436016355,
        1306827064, 3949387212, 3489808874, 4286832197, 3265308572,
         141116987, 1297632648,  912047691, 1975531039, 3234357167,
        1150743656, 3281707150, 1876459556,  628612596,  794205754,
        4251463549, 1935716005,  949009155, 2995840443, 4117919840,
         940021882,  240316975, 3191289405, 2914155301, 3015977553,
        3396447672,  605863491, 1168931830, 3340076030, 1846911956,
        3138137914, 1624856996,  272440712, 2352580807,  725879597,
        2190873206, 1754223968, 2419265249, 2685051388, 4228415737,
        1299645666,  935233826, 3382149214,  526141777, 1094201601,
        2927772930, 1261497186, 3858178418, 3775270750,  143926775,
        1917507826,   21511861, 2527197055, 1590843505,  930243495,
        1242050458, 3344852947, 1432380310,  869146594, 1725547267,
        1549005193, 3907923827,   72201198,  952190829, 2035050214,
        2408126925, 1433397210,   776

### **np.random.seed()**

In [16]:
#Seed The Generator
np.random.seed(10)

In [17]:
np.random.rand()
#The generator creates a random number based on the seed value, 
#so if the seed value is 10, you will always get 0.771320643266746 as 
#the first number

0.771320643266746